export const CATEGORIES_ACTION_TYPE = {
	SET_CATEGORIES: "SET_CATEGORIES",
	FETCH_CATEGORY_START: "FETCH_CATEGORY_START",
	FETCH_CATOGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
	FETCH_CATOGORY_FAILED: "FETCH_CATEGORY_FAILED",
};
